// Courtesy of http://hamelot.io/visualization/opengl-glsl-shader-as-a-string/

#include <filesystem>
#include <fmt/core.h>
#include <fstream>
#include <regex>

using namespace std;
namespace fs = std::filesystem;

void add_header_contents(const fs::path& source_file, ofstream& ofs) {
    static std::regex re_include("#include\\s+\"([\\w.]+)\"");

    auto ifs = std::ifstream(source_file.string());
    std::smatch include_match;
    std::string line;
    while (std::getline(ifs, line)) {
        if (std::regex_match(line, include_match, re_include)) {
            std::string inc_name = include_match[1];
            auto inc_path = source_file.parent_path() / inc_name;
            add_header_contents(inc_path, ofs);
            continue;
        }
        string c_line;
        c_line.reserve(line.size() + 100);
        c_line += "\"";
        for (size_t i = 0; i < line.size(); ++i) {
            char c = line[i];
            if ('"' == c)
                c_line += "\\\"";
            else if ('\\' == c)
                c_line += "\\\\";
            else
                c_line += c;
        }
        c_line += "\\n\"\n";
        ofs << c_line;
    }
}

int main(int argc, char** args) {
    if (argc != 3) {
        fmt::print("Usage: embed_shader <infile> <outfile>\n");
        exit(EXIT_FAILURE);
    }
    auto in_file = fs::path(args[1]);
    auto out_file = fs::path(args[2]);
    if (!fs::exists(in_file)) {
        fmt::print("Shader file {} does not exist!\n", in_file.string());
        exit(EXIT_FAILURE);
    }
    auto filename = in_file.filename();
    auto name = in_file.stem().string();
    auto ext = filename.extension().string();
    ext = ext.substr(1); // remove period
    auto array_name = fmt::format("{}_{}_shader", name, ext);

    auto ofs = std::ofstream(out_file);

    ofs << "// header file generated by lasagnaphil\n";
    ofs << fmt::format("#ifndef  TXT_HEADER_{}\n", array_name);
    ofs << fmt::format("#define  TXT_HEADER_{}\n", array_name);
    ofs << "\n\n";
    ofs << fmt::format("const char {} [] =\n", array_name);

    add_header_contents(in_file, ofs);

    ofs << ";\n";
    ofs << fmt::format("#endif  // #ifdef TXT_HEADER_{}\n", array_name);
}
