rule("compile_shaders")
    set_extensions(".vert", ".frag")
    on_load(function (target)
        local headerdir = path.join(target:autogendir(), "shaders")
        if not os.isdir(headerdir) then
            os.mkdir(headerdir)
        end
        target:add("includedirs", target:autogendir())
    end)
    before_buildcmd_file(function (target, batchcmds, shaderfile, opt)
        -- get header file
        local headerdir = path.join(target:autogendir(), "shaders")
        local name = path.basename(shaderfile)
        local ext = path.extension(shaderfile):ltrim('.')
        local headerfile = path.join(headerdir, string.format("%s.%s.h", name, ext))

        -- add commands
        batchcmds:show_progress(opt.progress, "${color.build.object}generating headers for %s", shaderfile)
        batchcmds:mkdir(headerdir)

        function add_header_contents(source, fout)
            local pat_include = "#include %s+\"([%w%.]+\")"
            local fin = io.open(source)
            for line in fin:lines() do
                local inc_name = string.gmatch(line, "#include \"(.+)\"")()
                if inc_name then
                    local inc_path = path.directory(source) .. '/' .. inc_name
                    add_header_contents(inc_path, fout)
                else
                    local c_line = line
                    c_line = c_line:gsub('"', '\\"')
                    c_line = '"' .. c_line .. '\\n"\n'
                    fout:write(c_line)
                end
            end
        end

        function embed_shader(in_file, out_file)
            local fout = io.open(out_file, 'w')
            local name = path.basename(in_file)
            local ext = path.extension(in_file):ltrim('.')
            local array_name = string.format('%s_%s_shader', name, ext)
            fout:write("// header file generated by lasagnaphil\n")
            fout:write(string.format("#ifndef  TXT_HEADER_%s\n", array_name))
            fout:write(string.format("#define  TXT_HEADER_%s\n", array_name))
            fout:write("\n\n")
            fout:write(string.format("const char %s [] =\n", array_name))

            add_header_contents(in_file, fout)

            fout:write(";\n")
            fout:write(string.format("#endif  // #ifdef TXT_HEADER_%s\n", array_name))
        end

        embed_shader(shaderfile, headerfile)

        -- add deps
        batchcmds:add_depfiles(shaderfile)
        batchcmds:set_depmtime(os.mtime(headerfile))
        batchcmds:set_depcache(target:dependfile(headerfile))
    end)
